function tool_printIdModel(handles, model)

%debug
assignin('base', 'handles', handles);
assignin('base', 'model', model);

s = {'A', ...
    num2str(model.A(1,:)), ...
    num2str(model.A(2,:)), ...
    ' ',...
    'B', ...
    num2str(model.B(1,:)), ...
    num2str(model.B(2,:)), ...
    ' ',...
    ['Dt: ' num2str(model.Dt * 1e3) ' mS']};%in milliseconds


set(handles.t_modelSelected, 'String', s);

end

